# https://pre-commit.com/#installation
default_stages: [pre-commit, pre-push]
default_language_version:
  python: python3
minimum_pre_commit_version: '3.2.0'
repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        name: run codespell
        description: check for misspelled words with codespell
        args: ['--skip=git']
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        name: run markdownlint
        description: lint Markdown files with markdownlint
        args: [--config=.github/linters/.markdown-lint.yml]
