# https://pre-commit.com/#installation
default_stages: [pre-commit, pre-push]
default_language_version:
  python: python3
minimum_pre_commit_version: '3.2.0'
repos:
  - repo: meta
    hooks:
      - id: identity
        name: run identity
        description: check to see if your identity is set
      - id: check-hooks-apply
        name: run check hooks apply
        description: useful when testing new hooks to see if they apply to the repository
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
        name: run check for case conflicts
      - id: check-illegal-windows-names
        name: run check for illegal windows names
      - id: check-json
        name: run check JSON
      - id: check-merge-conflict
        name: run check for merge conflicts
      - id: check-vcs-permalinks
        name: run check for vcs permalinks
      - id: check-yaml
        name: run check YAML
      - id: detect-aws-credentials
        name: run check for aws credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
        name: run check for private keys
      - id: end-of-file-fixer
        name: run end of file fixer
      - id: fix-byte-order-marker
        name: run fix byte order marker
      - id: forbid-submodules
        name: run forbid submodules
      - id: mixed-line-ending
        name: run check for mixed line endings
      - id: trailing-whitespace
        name: run check for trailing whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.3
    hooks:
      - id: gitleaks
        name: run gitleaks
        description: gitleaks detects hardcoded secrets in the repo
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        name: run codespell
        description: check for misspelled words with codespell
        args: ['--skip=git']
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        name: run markdownlint
        description: lint Markdown files with markdownlint
        args: [--config=.github/linters/.markdown-lint.yml]
  - repo: https://github.com/shssoichiro/oxipng
    rev: v9.1.4
    hooks:
      - id: oxipng
        name: run oxipng
        description: multithreaded PNG optimizer written in Rust
        args: ['-o', '4', '--strip', 'safe', '--alpha']
