---
name: 📚 Documentation Improvement
description: Suggest improvements to documentation
title: '[DOCS] '
labels: ['documentation', 'needs-triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve our documentation! Please fill out the form below.

  - type: textarea
    id: documentation-issue
    attributes:
      label: 📖 Documentation Issue
      description: What part of the documentation needs improvement?
      placeholder: Describe what needs to be improved...
    validations:
      required: true

  - type: checkboxes
    id: location
    attributes:
      label: 📍 Location
      description: Please specify which documentation needs improvement
      options:
        - label: README files
        - label: Code comments
        - label: Website contents
        - label: API documentation
        - label: Tutorial/Guide
        - label: Other
    validations:
      required: true

  - type: textarea
    id: specific-files
    attributes:
      label: 🔗 Specific Files/URLs
      description: List the specific files, pages, or sections that need improvement
      placeholder: |
        - path/to/file.md
        - https://example.com/page
    validations:
      required: false

  - type: textarea
    id: current-problem
    attributes:
      label: ❓ Current Problem
      description: What is unclear, missing, or incorrect in the current documentation?
      placeholder: Explain what's wrong with the current documentation...
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: ✏️ Suggested Improvement
      description: How should the documentation be improved?
      placeholder: |
        - What content should be added/changed
        - How it should be organized
        - Any examples that should be included
    validations:
      required: true

  - type: checkboxes
    id: target-audience
    attributes:
      label: 👥 Target Audience
      description: Who would benefit from this documentation improvement?
      options:
        - label: New contributors
        - label: End users
        - label: Chess players
        - label: Developers
        - label: Organization members
        - label: Other
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 🎯 Priority
      description: How important is this documentation improvement?
      options:
        - Critical - Blocking user success
        - High - Frequently needed information
        - Medium - Would be helpful to have
        - Low - Nice to have
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Any additional context, examples, or resources that might help with the improvement.
      placeholder: Any additional information that might help...
    validations:
      required: false
