---
name: 🤖 Pull Request Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  label:
    name: 🏷️ Auto-Label Pull Request
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Labeler
        uses: actions/labeler@v5.0.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: '.github/labeler.yml'
          sync-labels: true
