---
name: 🤖 Pull Request Labeler

"on":
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

permissions:
  contents: read

jobs:
  label:
    name: 🏷️ Auto-Label Pull Request
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Label Pull Request
        uses: actions/labeler@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: true
