---
name: 🦸 Super-Linter

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: 🧼 Run Super-Linter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write # To report GitHub Actions status checks

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
          fetch-depth: 0 # super-linter needs the full git history for file changes across commits

      - name: Super-Linter
        uses: super-linter/super-linter@4ce20838b8ab83717e78138c5b3a1407148e0918
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # To report GitHub Actions status checks
