name: 🧪 Test git clone
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  test-git-clone:
    timeout-minutes: 10
    name: 'Clone on ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest}
          - {os: ubuntu-22.04}
          - {os: macos-latest}
          - {os: windows-latest}
          - {os: windows-2022}
    steps:
      - name: 'Checkout ${{ github.ref }} ( ${{ github.sha }} )'
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
